const APP_VERSION="1.3.2";
const translations={
 en:{htmlLang:"en",eyebrow:"Smart shopping",title:"Shopping List",settingsTitle:"Settings",languageLabel:"Language",addTitle:"Add product",productName:"Product",priceOne:"Price for 1 item",quantity:"Quantity",addButton:"+ Add",totalItems:"Total quantity",boughtItems:"Bought quantity",spent:"Spent",listTitle:"Products",clear:"Clear",empty:"No products yet.",priceLabel:"Price for 1 item",quantityLabel:"Quantity",totalLabel:"Total",deleteLabel:"Delete",minusLabel:"Decrease quantity",plusLabel:"Increase quantity",defaultProduct:"Milk",purchaseTitle:"Complete purchase",storeName:"Store",purchaseDate:"Date",savePurchase:"Save checked items to history",openHistory:"Purchase history",historyTitle:"Purchase history",historyEmpty:"No saved purchases yet.",selectedTotal:"Selected total",share:"Share",print:"Print / PDF",receiptItems:"Items",saved:"✓ Purchase saved",needStore:"Enter store name",needItems:"Check at least one product",selectedReceipts:"Selected receipts",copied:"Copied"},
 ru:{htmlLang:"ru",eyebrow:"Умные покупки",title:"Список покупок",settingsTitle:"Настройки",languageLabel:"Язык",addTitle:"Добавить товар",productName:"Товар",priceOne:"Цена за 1 штуку",quantity:"Количество",addButton:"+ Добавить",totalItems:"Общее количество",boughtItems:"Куплено штук",spent:"Потрачено",listTitle:"Товары",clear:"Очистить",empty:"Пока товаров нет.",priceLabel:"Цена за 1 шт",quantityLabel:"Количество",totalLabel:"Итого",deleteLabel:"Удалить",minusLabel:"Уменьшить количество",plusLabel:"Увеличить количество",defaultProduct:"Молоко",purchaseTitle:"Завершить покупку",storeName:"Магазин",purchaseDate:"Дата",savePurchase:"Сохранить отмеченные товары",openHistory:"История покупок",historyTitle:"История покупок",historyEmpty:"Сохранённых покупок пока нет.",selectedTotal:"Итог выбранных",share:"Поделиться",print:"Печать / PDF",receiptItems:"Товары",saved:"✓ Покупка сохранена",needStore:"Укажи магазин",needItems:"Отметь галочкой хотя бы один товар",selectedReceipts:"Выбрано чеков",copied:"Скопировано"},
 ka:{htmlLang:"ka",eyebrow:"ჭკვიანი საყიდლები",title:"საყიდლების სია",settingsTitle:"პარამეტრები",languageLabel:"ენა",addTitle:"პროდუქტის დამატება",productName:"პროდუქტი",priceOne:"ფასი 1 ცალზე",quantity:"რაოდენობა",addButton:"+ დამატება",totalItems:"სრული რაოდენობა",boughtItems:"ნაყიდი რაოდენობა",spent:"დახარჯულია",listTitle:"პროდუქტები",clear:"გასუფთავება",empty:"პროდუქტები ჯერ არ არის.",priceLabel:"ფასი 1 ცალზე",quantityLabel:"რაოდენობა",totalLabel:"ჯამი",deleteLabel:"წაშლა",minusLabel:"რაოდენობის შემცირება",plusLabel:"რაოდენობის გაზრდა",defaultProduct:"რძე",purchaseTitle:"შენაძენის დასრულება",storeName:"მაღაზია",purchaseDate:"თარიღი",savePurchase:"მონიშნულის შენახვა",openHistory:"შენაძენების ისტორია",historyTitle:"შენაძენების ისტორია",historyEmpty:"შენახული შენაძენები ჯერ არ არის.",selectedTotal:"არჩეულის ჯამი",share:"გაზიარება",print:"ბეჭდვა / PDF",receiptItems:"პროდუქტები",saved:"✓ შენაძენი შენახულია",needStore:"მიუთითე მაღაზია",needItems:"მონიშნე მინიმუმ ერთი პროდუქტი",selectedReceipts:"არჩეული ჩეკები",copied:"დაკოპირდა"},
 da:{htmlLang:"da",eyebrow:"Smart indkøb",title:"Indkøbsliste",settingsTitle:"Indstillinger",languageLabel:"Sprog",addTitle:"Tilføj vare",productName:"Vare",priceOne:"Pris for 1 stk",quantity:"Antal",addButton:"+ Tilføj",totalItems:"Antal i alt",boughtItems:"Købt antal",spent:"Brugt",listTitle:"Varer",clear:"Ryd",empty:"Ingen varer endnu.",priceLabel:"Pris for 1 stk",quantityLabel:"Antal",totalLabel:"I alt",deleteLabel:"Slet",minusLabel:"Reducer antal",plusLabel:"Øg antal",defaultProduct:"Mælk",purchaseTitle:"Afslut køb",storeName:"Butik",purchaseDate:"Dato",savePurchase:"Gem markerede varer",openHistory:"Købshistorik",historyTitle:"Købshistorik",historyEmpty:"Ingen gemte køb endnu.",selectedTotal:"Valgt total",share:"Del",print:"Print / PDF",receiptItems:"Varer",saved:"✓ Køb gemt",needStore:"Indtast butik",needItems:"Marker mindst én vare",selectedReceipts:"Valgte kvitteringer",copied:"Kopieret"}
};
const currencies={en:{symbol:"€",position:"before"},ru:{symbol:"₽",position:"after"},ka:{symbol:"₾",position:"after"},da:{symbol:"kr",position:"after"}};
const storageKey="shopping-list-app-v1",historyStorageKey="shopping-list-history-v1";
function safeParseArray(key){try{const v=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(v)?v:[]}catch(e){localStorage.removeItem(key);return[]}}
function makeId(){return window.crypto&&typeof window.crypto.randomUUID==="function"?window.crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}
const state={language:localStorage.getItem("shoppingLanguage")||"en",items:safeParseArray(storageKey),history:safeParseArray(historyStorageKey),selectedHistoryIds:new Set()};
if(!translations[state.language])state.language="en";
const $=id=>document.getElementById(id);
const itemForm=$("itemForm"),nameInput=$("name"),priceInput=$("price"),quantityInput=$("quantity"),storeNameInput=$("storeName"),purchaseDateInput=$("purchaseDate"),savePurchaseBtn=$("savePurchaseBtn"),purchaseStatus=$("purchaseStatus"),itemsList=$("itemsList"),emptyState=$("emptyState"),totalItems=$("totalItems"),boughtItems=$("boughtItems"),spentMoney=$("spentMoney"),clearBtn=$("clearBtn"),settingsBtn=$("settingsBtn"),closeSettingsBtn=$("closeSettingsBtn"),settingsPanel=$("settingsPanel"),openHistoryBtn=$("openHistoryBtn"),historyPanel=$("historyPanel"),closeHistoryBtn=$("closeHistoryBtn"),historyList=$("historyList"),historyEmpty=$("historyEmpty"),selectedHistoryTotal=$("selectedHistoryTotal"),printArea=$("printArea");
const languageButtons=document.querySelectorAll(".language-option");
let statusTimer=null;
function todayISO(){return new Date().toISOString().slice(0,10)}
if(purchaseDateInput&&!purchaseDateInput.value)purchaseDateInput.value=todayISO();
function getDict(){return translations[state.language]||translations.en}
function formatMoney(value){const c=currencies[state.language]||currencies.en,loc=state.language==="ru"?"ru-RU":state.language==="ka"?"ka-GE":state.language==="da"?"da-DK":"en-US",n=Number(value||0),val=n.toLocaleString(loc,{minimumFractionDigits:n%1===0?0:2,maximumFractionDigits:2});return c.position==="before"?`${c.symbol}${val}`:`${val} ${c.symbol}`}
function saveState(){localStorage.setItem(storageKey,JSON.stringify(state.items));localStorage.setItem(historyStorageKey,JSON.stringify(state.history));localStorage.setItem("shoppingLanguage",state.language)}
function escapeHtml(value){return String(value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;")}
function showStatus(text,isError=false){if(!purchaseStatus)return;purchaseStatus.textContent=text;purchaseStatus.style.display="block";purchaseStatus.style.color=isError?"#b91c1c":"#16a34a";purchaseStatus.style.fontWeight="900";purchaseStatus.style.margin="10px 0 0";clearTimeout(statusTimer);statusTimer=setTimeout(()=>{purchaseStatus.textContent="";purchaseStatus.style.display="none"},3000)}
function applyLanguage(){const d=getDict();document.documentElement.lang=d.htmlLang;document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(d[k])el.textContent=d[k]});if(nameInput)nameInput.placeholder=d.defaultProduct;languageButtons.forEach(b=>b.classList.toggle("active",b.dataset.lang===state.language))}
function itemTotal(item){return Number(item.price||0)*Number(item.quantity||0)}
function receiptTotal(receipt){return(receipt.items||[]).reduce((s,i)=>s+itemTotal(i),0)}
function receiptQuantity(receipt){return(receipt.items||[]).reduce((s,i)=>s+Number(i.quantity||0),0)}
function renderItems(){if(!itemsList||!emptyState)return;const d=getDict();itemsList.innerHTML="";emptyState.style.display=state.items.length?"none":"block";state.items.forEach(item=>{const article=document.createElement("article");article.className=`item-card ${item.done?"done":""}`;article.innerHTML=`<input class="check" type="checkbox" ${item.done?"checked":""} aria-label="${d.boughtItems}"/><div><h3 class="item-name"></h3><div class="item-details"><span>${d.priceLabel}: ${formatMoney(item.price)}</span></div><div class="quantity-control" aria-label="${d.quantityLabel}"><button class="qty-btn minus-btn" type="button" aria-label="${d.minusLabel}">−</button><span class="qty-number">${Number(item.quantity||1)}</span><button class="qty-btn plus-btn" type="button" aria-label="${d.plusLabel}">+</button></div><div class="item-total">${d.totalLabel}: ${formatMoney(itemTotal(item))}</div></div><button class="delete-btn" type="button" aria-label="${d.deleteLabel}">×</button>`;article.querySelector(".item-name").textContent=item.name||"";article.querySelector(".check").addEventListener("change",()=>toggleItem(item.id));article.querySelector(".minus-btn").addEventListener("click",()=>changeQuantity(item.id,-1));article.querySelector(".plus-btn").addEventListener("click",()=>changeQuantity(item.id,1));article.querySelector(".delete-btn").addEventListener("click",()=>deleteItem(item.id));itemsList.appendChild(article)})}
function renderSummary(){if(!totalItems||!boughtItems||!spentMoney)return;const totalQ=state.items.reduce((s,i)=>s+Number(i.quantity||0),0),boughtQ=state.items.filter(i=>i.done).reduce((s,i)=>s+Number(i.quantity||0),0),spent=state.items.filter(i=>i.done).reduce((s,i)=>s+itemTotal(i),0);totalItems.textContent=totalQ;boughtItems.textContent=boughtQ;spentMoney.textContent=formatMoney(spent)}
function renderHistory(){if(!historyList||!historyEmpty)return;const d=getDict();historyList.innerHTML="";historyEmpty.style.display=state.history.length?"none":"block";state.history.forEach(receipt=>{const card=document.createElement("article");card.className="history-card";const checked=state.selectedHistoryIds.has(receipt.id)?"checked":"";const itemsHtml=(receipt.items||[]).map(item=>`<span>${escapeHtml(item.name)} — ${item.quantity} × ${formatMoney(item.price)} = ${formatMoney(itemTotal(item))}</span>`).join("");card.innerHTML=`<input class="check history-check" type="checkbox" ${checked}/><div><h3>${escapeHtml(receipt.store)}</h3><div class="history-meta">${escapeHtml(receipt.date)} · ${d.receiptItems}: ${receiptQuantity(receipt)}</div><div class="history-items">${itemsHtml}</div><div class="history-total-line">${d.totalLabel}: ${formatMoney(receiptTotal(receipt))}</div><div class="history-actions"><button class="history-action-btn share-btn" type="button">📤 ${d.share}</button><button class="history-action-btn print-btn" type="button">🖨 ${d.print}</button></div></div>`;card.querySelector(".history-check").addEventListener("change",e=>toggleReceiptSelection(receipt.id,e.target.checked));card.querySelector(".share-btn").addEventListener("click",()=>shareReceipt(receipt));card.querySelector(".print-btn").addEventListener("click",()=>printReceipt(receipt));historyList.appendChild(card)});renderSelectedHistoryTotal()}
function renderSelectedHistoryTotal(){if(!selectedHistoryTotal)return;const selected=state.history.filter(r=>state.selectedHistoryIds.has(r.id)),total=selected.reduce((s,r)=>s+receiptTotal(r),0);selectedHistoryTotal.textContent=`${getDict().selectedReceipts}: ${selected.length} · ${formatMoney(total)}`}
function render(){applyLanguage();renderItems();renderSummary();renderHistory();saveState()}
function addItem(event){event.preventDefault();const name=nameInput.value.trim(),price=Number(priceInput.value),quantity=Number(quantityInput.value);if(!name||price<0||quantity<1)return;state.items.unshift({id:makeId(),name,price,quantity,done:false});itemForm.reset();quantityInput.value=1;nameInput.focus();render()}
function toggleItem(id){state.items=state.items.map(item=>item.id===id?{...item,done:!item.done}:item);render()}
function changeQuantity(id,delta){state.items=state.items.map(item=>item.id===id?{...item,quantity:Math.max(1,Number(item.quantity||1)+delta)}:item);render()}
function deleteItem(id){state.items=state.items.filter(item=>item.id!==id);render()}
function savePurchase(){const d=getDict(),store=storeNameInput.value.trim(),date=purchaseDateInput.value||todayISO(),checkedItems=state.items.filter(item=>item.done);if(!store)return showStatus(d.needStore,true);if(!checkedItems.length)return showStatus(d.needItems,true);const receipt={id:makeId(),store,date,items:checkedItems.map(item=>({...item,done:true})),createdAt:new Date().toISOString()};state.history.unshift(receipt);state.selectedHistoryIds.add(receipt.id);state.items=state.items.filter(item=>!item.done);storeNameInput.value="";purchaseDateInput.value=todayISO();render();showStatus(d.saved,false)}
function toggleReceiptSelection(id,selected){if(selected)state.selectedHistoryIds.add(id);else state.selectedHistoryIds.delete(id);renderSelectedHistoryTotal()}
function receiptText(receipt){const d=getDict(),lines=["Shopping List App",receipt.store,`${d.purchaseDate}: ${receipt.date}`,"",`${d.receiptItems}:`];(receipt.items||[]).forEach(item=>lines.push(`${item.name} — ${item.quantity} × ${formatMoney(item.price)} = ${formatMoney(itemTotal(item))}`));lines.push("",`${d.totalLabel}: ${formatMoney(receiptTotal(receipt))}`);return lines.join("\n")}
async function shareReceipt(receipt){const text=receiptText(receipt);if(navigator.share){try{await navigator.share({title:`${receipt.store} ${receipt.date}`,text})}catch(e){}return}if(navigator.clipboard&&navigator.clipboard.writeText){await navigator.clipboard.writeText(text);alert(getDict().copied)}else alert(text)}
function printReceipt(receipt){if(!printArea)return;printArea.innerHTML=`<pre>${escapeHtml(receiptText(receipt))}</pre>`;window.print()}
function openSettings(){settingsPanel.classList.add("open");settingsPanel.setAttribute("aria-hidden","false")}
function closeSettings(){settingsPanel.classList.remove("open");settingsPanel.setAttribute("aria-hidden","true")}
function openHistory(){closeSettings();historyPanel.classList.add("open");historyPanel.setAttribute("aria-hidden","false");renderHistory()}
function closeHistory(){historyPanel.classList.remove("open");historyPanel.setAttribute("aria-hidden","true")}
if(settingsBtn)settingsBtn.addEventListener("click",openSettings);if(closeSettingsBtn)closeSettingsBtn.addEventListener("click",closeSettings);if(settingsPanel)settingsPanel.addEventListener("click",e=>{if(e.target===settingsPanel)closeSettings()});if(openHistoryBtn)openHistoryBtn.addEventListener("click",openHistory);if(closeHistoryBtn)closeHistoryBtn.addEventListener("click",closeHistory);if(historyPanel)historyPanel.addEventListener("click",e=>{if(e.target===historyPanel)closeHistory()});languageButtons.forEach(button=>button.addEventListener("click",()=>{state.language=button.dataset.lang;closeSettings();render()}));if(itemForm)itemForm.addEventListener("submit",addItem);if(savePurchaseBtn)savePurchaseBtn.addEventListener("click",savePurchase);if(clearBtn)clearBtn.addEventListener("click",()=>{state.items=[];render()});render();
